### ISSUE TITLE
Salvaged Memories bug : no images pulled

### ISSUE THREAD

**Issue by kapazoglou** [axmccx/proxynexus#12]
Hi, 

I was trying to make some earlier decks and it seems that all the cards that were published in Salvaged Memories (29001-29018 on netrunnerDB) do not show in the generator and break the whole process, probably because they use new ids to pull the images rather than the original ids. [edit: I had a look at past issues and this must be similar to #3 ]

I think it may be solved if the request for the image calls it with it's earlier netrunnerDB id number rather than the newer one. That could probably solve the issue when NISEI rotates other older cards back in.

Cheers,
Mano

 P.S. Just in case I made a list of the affected cards below:

Medium : 29001 -> 01010
Parasite : 29002 -> 01012
e3 Feedback Implants : 29003 -> 02024
Cache : 29004 -> 06037
Indexing : 29005 -> 02106
Cerberus "Lady" H1 : 29006 -> 06099
Lucky Find : 29007 -> 04109
Prepaid VoicePAD : 29008 -> 04029
NEXT Bronze : 29009 -> 04011
NEXT Silver : 29010 -> 06002
Hostile Infrastructure : 29011 -> 06083
Turtlebacks : 29012 -> 06106
Sweeps Week : 29013 -> 04076
SanSan City Grid : 29014 -> 01092
Executive Boot Camp : 29015 -> 06088
Scorched Earth : 29016 -> 01099
Excalibur : 29017 -> 06111
Subliminal Messaging : 29018 -> 04100

**Comment by axmccx** [comment]
Thank you so much for the heads up!! This will be a simple fix in how I setup the image storage. That list you you included helps tremendously.

**Comment by kapazoglou** [comment]
Wow this was quick! Happy to help, and thank you so much for putting this amazing tool together, I wouldn't have gotten into Netrunner without it 😄

**Comment by axmccx** [comment]
I just updated the storage for these new card IDs and pushed a small update so that this doesn't break the alt art selection for some of these cards. Thanks for using the site, I'm glad you've found it useful. :)

**Comment by kapazoglou** [comment]
Works like a charm, thank you!
