### ISSUE TITLE
Outdated Instructions

### ISSUE THREAD

**Issue by jedshuang** [axmccx/proxynexus#18]
Hi, I recently went through the process of using proxynexus to make some cards and I came across these two points in the instructions:

1) For step 4., Make Playing Cards no longer have `300gsm` and `330gsm` as card stock options. My assumption is that they have been replaced by the `(S30)` and `(S33)` options. I received my `(S30)` deck and it was more than adequate for gameplay.

2) For step 6., there is a small typo: the button should read `start your design` and not `start you design`.

Thank you for making such a great service, it is beautifully made and works like a charm.

**Comment by axmccx** [comment]
I just pushed the corrections, thank you!!
