### ISSUE TITLE
Stuck at Waiting in queue...

### ISSUE THREAD

**Issue by SPavuna** [axmccx/proxynexus#24]
Heya!

I've used your service before and this was never a problem, so I imagine there's some kind of a problem or some dependency is down?

After pressing "Generate Proxies", I get moved to "Waiting in queue..." and then nothing happens, except occasionally "Lost connection to server, try refreshing the page" at the top of the screen for 1 second, and then it disappears.

**Comment by SPavuna** [comment]
Heya, false alarm, there was some problem at my end, restarting Chrome fixed whatever was wrong.

Sorry for taking your time, great product <3

**Comment by axmccx** [comment]
All good, thanks anyways for bringing it up! :D
