### ISSUE TITLE
Generate PDF hangs and then fails

### ISSUE THREAD

**Issue by gannicottb** [axmccx/proxynexus#29]
To reproduce:

Click on 'Generate Proxies'
'Waiting in queue' is displayed for some time, before eventually timing out.

**Comment by Erlendsa91** [comment]
Its happening again. Could you try to reboot it again? @axmccx 

Thanks

**Comment by axmccx** [comment]
Done!

**Comment by Erlendsa91** [comment]
Hi. I see that it worked earlier in statistics, but it might have broke again? Its just hanging on waiting in queue. And when checking statistics it immidiacly is listed as Cache Expired. 

But I do see downloads sucsessful, but seeam to have broke again? @axmccx
