### ISSUE TITLE
Issues with the new Magnum Opus Cards

### ISSUE THREAD

**Issue by 5N00P1** [axmccx/proxynexus#3]
Decks that contain Magnum Opus Cards, get an empty card. e.g. Slot Machine or Border Control as you can see in the attached screenshot. I assume it's how the scans are stored from Lepsis Magna and that NRDB uses the new cards.

![image](https://user-images.githubusercontent.com/5659287/68701078-53ecb600-0586-11ea-82fd-eb7665271d28.png)

This deck created the screenshot:
https://netrunnerdb.com/en/decklist/57683/quest-aginfusion-5th-at-uk-nats-1st-at-pos

**Comment by axmccx** [comment]
Ah, looks like NRDB is using the prefix '28' on the Magnum Opus reprints. I'll need to add this. Thanks for pointing this out!

**Comment by axmccx** [comment]
Fixed
