### ISSUE TITLE
lost connection to server

### ISSUE THREAD

**Issue by Iamgob** [axmccx/proxynexus#30]
Everytime i try generating pdfs, i get a message after about 20 seconds in red saying connection to server lost, try refreshing your browser. 

Ive tried refreshing several times and also trying in another web browser but ive found no solutions so far...

**Comment by axmccx** [comment]
Hey, sorry for missing this. Are you still having issues?

**Comment by MHGray** [comment]
I am getting this same issue. I've tried on Chrome, Firefox and Edge. Each gets the same error message. I've taken a screen shot with the dev tools for Chrome open so you can see the error.
![image](https://user-images.githubusercontent.com/8196735/182969760-2d0c12ba-3da3-44bf-99bc-82a0a559e310.png)  

After the error message comes up, the Generate Proxies button becomes lit up again (when 'Connected' is console logged). 

The cards I have selected are all the 'New' variant that comes up by default, though I've tried with the Legacy version selected and get the same error.

The Cards I entered in:
```
1x The Twinning
1x Revolver
3x Into the Depths
1x Hyperbaric
3x Propeller
```
