### ISSUE TITLE
Midnight Sun not supported

### ISSUE THREAD

**Issue by PreNic** [axmccx/proxynexus#33]
It would be great to have the support for Midnight Sun. Ashes and Gateway are supported and sometimes it is really helpful (other than environment friendly) to make a single page with the required cards rather than printing full pages from the Nisei's PDF.

**Comment by axmccx** [comment]
Thanks for the heads up, I've been out of the Netrunner loop and didn't notice new cards were released. No code change should be required, just a matter of (manually) saving the pictures files from the PDFs NISEI posted, naming them all by their NetrunnerDB IDs with a copy for the PDF and another for the website preview, (eg, 33001_os_pdf.jpg, 33001_os_prev.jpg, 33002_os_pdf.jpg, etc). 

I can try to do this sometime tomorrow, but if anyone can help save this files and provide them to me, would be a huge help. Thanks!

**Comment by PreNic** [comment]
Thanks, I thought that the images were directly grabbed from NetrunnerDB, at least for the Nisei ones that don't have any FFG mark. I am not sure if they will have the same quality but you can easily download all the new cards getting the images stored at https://static.nrdbassets.com/v1/large/CARDNUMBER.jpg. For example, this would be Padma that is card number 33021 -> https://static.nrdbassets.com/v1/large/33021.jpg

**Comment by axmccx** [comment]
I just had a look, and the quality from NetrunnerDB is not the same. They also have rounded corners, where the PDF images are squared off and are higher resolution.  I've always used the images from PDFs in order to get the closest match to what NISEI provides. I know it's a tedious process to save all the images from the PDFs, but I can try to set some time aside tomorrow.

**Comment by axmccx** [comment]
@PreNic I've added Midnight Sun images. Turns out it needed a DB update too. I'll be pushing a commit tomorrow to track the changes in the DB seeds, but the website should be loading the new images now.

**Comment by PreNic** [comment]
Great, thank you!

**Comment by PreNic** [comment]
@axmccx I have seen there the wrong image on Anemone; it shows Hákarl 1.0 instead

**Comment by axmccx** [comment]
Nice catch! Thanks for finding this. I had made two copies of Hákarl 1.0, and one had the same ID as Anemone.I've fixed the image files, you may need to clear your browser cache, but it appears to be correct for me now.
