### ISSUE TITLE
Make German R&R available?

### ISSUE THREAD

**Issue by 5N00P1** [axmccx/proxynexus#4]
Hey,

currently working on making R&R in German available in the same way as Core 2019.
Could you make that available too? Should be fully available today.

**Comment by axmccx** [comment]
Sure, I'll try to add these at some point. If not this coming weekend then likely the next. Also, I noticed that this card is the English version, [049_ArellaSalvatore.JPG](https://drive.google.com/open?id=1FnhLQcxwaoYv_zq0-ZKkCPAMwMydKEDY)

**Comment by 5N00P1** [comment]
Thank you so much!
We are working on other projects too so I hope we are going to have in some month the full legal card pool scanned, but I'm not sure how long that will take.

Thanks for the notification of Arella, can confirm this and trigger actions to replace it properly.

**Comment by axmccx** [comment]
R&R is now available as the set "Herrschaft und Traum". Sorry this took so long.

**Comment by 5N00P1** [comment]
I think it would be good to list the language in brackets, as currently it's hard to finde and when we manage to add other sets things will not get easier!
So I would suggest "Herrschaft und Traum (de)".
