### ISSUE TITLE
Lost connection to server, try refreshing your browser

### ISSUE THREAD

**Issue by MarcusCastor** [axmccx/proxynexus#45]
Hello everybody! 
Everytime I try to generate proxys the process seems to get stuck and after a minute or so the connection gets lost and no popup opens.
I tried the hp with Edge, Chrome, FireFox on my W11 maschine and with Safari on my mobile.
Yesterday it worked just fine.
Any idea what I´m doing wrong?
Thanks for any help and for this great project!

![2023-01-25 20_23_42-Proxy Nexus – Mozilla Firefox](https://user-images.githubusercontent.com/41427341/214667705-c2c0481a-e282-4b70-af92-a483f3a62186.png)

**Comment by axmccx** [comment]
Hey, the website's backend design is pretty bad. I've setup some bandaids fixes that clears caches and reboots the server every night, or when its storage is about to run out from caches building up. I just ran my cleanup+reboot script on it now, should come back in a couple of minutes. If it happens again and I'm unavailable, the site should clear itself up within 24 hours. 

Hopefully one day I'll get around to implementing my ideas for a proper redesign.

**Comment by MarcusCastor** [comment]
Omg thank you for this crazy fast answer and help!
It seems to work just fine!
Thank you again - extraordinary support!
