### ISSUE TITLE
Parhelion cards not yet supported

### ISSUE THREAD

**Issue by francescopellegrini** [axmccx/proxynexus#51]
Hi, I noticed Parhelion cards cannot be found on ProxyNexus: any way I can help with it?

**Comment by axmccx** [comment]
hello! thanks for offering to help. I've been busy lately and haven't gotten around to making the update. First, it requires saving all the image files from the NSG print and play PDFs. I just use adobe reader and save them one by one. Then I need to upload them to storage.
I have various python scripts in the misc folder I've used to help automate renaming the pictures files to fit the naming convention the site uses, and for the generation of the DB seed files. If you look at my [midnight sun commit](https://github.com/axmccx/proxynexus/commit/4d375205ce6a21dd1752c1f32b562ad009626d97), hopefully it conveys the updates that are required.

**Comment by francescopellegrini** [comment]
Hi @axmccx , are you going to add Parhelion cards soon? 🙏

**Comment by francescopellegrini** [comment]
Hi @axmccx , are The Automata Initiative (TAI) cards going to be added in the near future?

**Comment by axmccx** [comment]
I've added both sets of cards. Sorry it took so long.

**Comment by francescopellegrini** [comment]
Thank you so much, appreciate it! ❤️
