### ISSUE TITLE
Missing cards

### ISSUE THREAD

**Issue by Olganita** [axmccx/proxynexus#55]
Hi,

I noticed four cards don't show up :

-“Pretty” Mary da Silva
- Ken “Express” Tenma: Disappeared Clone
- Aesop’s Pawnshop
- The Wizard’s Chest

Thanks

**Comment by axmccx** [comment]
https://discord.com/channels/425105101451952128/425105101451952130/1238550366467919984

![IMG_6007](https://github.com/axmccx/proxynexus/assets/3931007/a1ceddcf-611c-402e-899e-2e708c2f7c98)
