### ISSUE TITLE
Feature request: Add different page format support

### ISSUE THREAD

**Issue by LargoW** [axmccx/proxynexus#57]
My country uses mainly DINA4 instead of Letter and Letter is really hard to come by. I usually shrink the pages by 94% as a workaround, but exporting to PDF DIN A4 instead would be ace.

**Comment by axmccx** [comment]
Is that different from this A4 format? 
![IMG_6904](https://github.com/axmccx/proxynexus/assets/3931007/0a868578-da18-428b-9edb-807122347c76)

**Comment by LargoW** [comment]
No, not at all. I simply missed that there is a "Settings Tab" and expected it somehow as an option during export...
