### ISSUE TITLE
Wrong amount of Cards for German System Core 2019

### ISSUE THREAD

**Issue by 5N00P1** [axmccx/proxynexus#6]
The German version of System Core 2019 has the wrong number of cards for some of the cards (all Anarch).
The following cards are wrong:
- Ice Carver, currently 3 should be 1
- Xanadu, currently 2 should be 1
- Corroder, currently 2 should be 3
- Force of Nature, currently 3 should be 2
- Mimic, currently 1 should be 3
- Lamprey, currently 1 should be 2

**Comment by axmccx** [comment]
Thanks for pointing this out! Should be fixed now.
